Repository pyxem/kikuchipy, pull requests merged in 2020-09, with the labels that each got.

#207 Simplify GitHub issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: maintenance

#215 Document EBSD reference frames
  doc/_static/image/change_scan_pattern_size/change_pattern_size.jpg
  doc/_static/image/concatenate_images.sh
  doc/_static/image/create_images.sh
  doc/_static/image/doc_feature_maps_images.py
  doc/_static/image/doc_processing_images.py
  doc/_static/image/doc_reference_frames.py
  doc/_static/image/doc_virtual_imaging.py
  doc/_static/image/doc_visualize_images.py
  doc/_static/image/feature_maps/iq.png
  doc/_static/image/pattern_processing/average_neighbour_pattern.jpg
  doc/_static/image/pattern_processing/contrast_stretching.jpg
  doc/_static/image/pattern_processing/dynamic_correction.jpg
  doc/_static/image/pattern_processing/fft_filter_highlowpass_result.jpg
  doc/_static/image/pattern_processing/fft_filter_laplacian.jpg
  doc/_static/image/pattern_processing/fft_filter_laplacian_after.png
  doc/_static/image/pattern_processing/get_dynamic_background.jpg
  doc/_static/image/pattern_processing/kernel_circular_54.png
  doc/_static/image/pattern_processing/kernel_gaussian_std1.png
  doc/_static/image/pattern_processing/rescale_intensities.jpg
  doc/_static/image/pattern_processing/static_correction.jpg
  doc/_static/image/pattern_processing/window_circular_54.png
  doc/_static/image/pattern_processing/window_gaussian_std1.png
  doc/_static/image/reference_frames/detector.jpg
  doc/_static/image/reference_frames/detector.png
  doc/_static/image/reference_frames/detector.svg
  doc/_static/image/reference_frames/detector_gnomonic_coordinates.jpg
  doc/_static/image/reference_frames/detector_sample_geometry.png
  doc/_static/image/reference_frames/detector_sample_geometry.svg
  doc/_static/image/remove_images_not_in_docs.sh
  doc/_static/image/virtual_backscatter_electron_imaging/images.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/plot_grid.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/rgba_image.jpg
  doc/_static/image/visualizing_patterns/om_navigation.jpg
  doc/_static/image/visualizing_patterns/orientation_map.jpg
  doc/_static/image/visualizing_patterns/orientation_map.png
  doc/_static/image/visualizing_patterns/orientation_similarity_map.png
  doc/_static/image/visualizing_patterns/osm_navigation.jpg
  doc/_static/image/visualizing_patterns/vbse_navigation.jpg
  doc/_static/style.css
  doc/changelog.rst
  doc/conf.py
  doc/index.rst
  doc/reference_frames.rst
  kikuchipy/conftest.py
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/detectors/tests/test_ebsd_detector.py
  kikuchipy/generators/tests/test_ebsd_simulation_generator.py
Labels: documentation, tests

#216 Depend on orix v0.5, use spherical coordiantes from Vector3d directly
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/projections/gnomonic_projection.py
  kikuchipy/projections/hesse_normal_form.py
  kikuchipy/projections/lambert_projection.py
  kikuchipy/projections/spherical_projection.py
  kikuchipy/projections/tests/test_gnomonic_projection.py
  kikuchipy/projections/tests/test_hesse_normal_form.py
  kikuchipy/projections/tests/test_lambert_projection.py
  kikuchipy/projections/tests/test_spherical_projection.py
  kikuchipy/simulations/features.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
  kikuchipy/simulations/tests/test_features.py
  setup.py
Labels: bug, maintenance

#219 Complete tests for EBSDSimulationGenerator
  doc/changelog.rst
  doc/conf.py
  doc/reference.rst
  kikuchipy/conftest.py
  kikuchipy/generators/__init__.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/generators/tests/test_ebsd_simulation_generator.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
Labels: documentation, enhancement, tests

#220 Use diffsims for electron scattering and diffraction
  doc/changelog.rst
  kikuchipy/conftest.py
  kikuchipy/crystallography/__init__.py
  kikuchipy/crystallography/atomic_scattering_factor.py
  kikuchipy/crystallography/atomic_scattering_parameters.py
  kikuchipy/crystallography/reciprocal_lattice_point.py
  kikuchipy/crystallography/structure_factor.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/simulations/features.py
  setup.py
Labels: maintenance

#221 Array creation in filters.window.distance_to_origin is not ragged anymore
  doc/changelog.rst
  kikuchipy/filters/window.py
Labels: bug

#222 Rename "svd" to "SVD" in EBSD decomposition tests
  kikuchipy/signals/tests/test_ebsd.py
Labels: tests

#218 Lambert update
  kikuchipy/projections/gnomonic_projection.py
  kikuchipy/projections/lambert_projection.py
  kikuchipy/projections/spherical_projection.py
  kikuchipy/projections/tests/test_lambert_projection.py
  kikuchipy/signals/ebsd.py
Labels: bug

#223 Document and test KikuchiBand class, restructure and add to the API documentation
  doc/conf.py
  doc/contributing.rst
  doc/installation.rst
  doc/pattern_processing.rst
  doc/reference.rst
  doc/reference_frames.rst
  doc/visualizing_patterns.rst
  kikuchipy/__init__.py
  kikuchipy/crystallography/__init__.py
  kikuchipy/detectors/__init__.py
  kikuchipy/draw/__init__.py
  kikuchipy/filters/__init__.py
  kikuchipy/filters/window.py
  kikuchipy/generators/__init__.py
  kikuchipy/generators/_transfer_axes.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/generators/util/tests/__init__.py
  kikuchipy/generators/util/tests/test_virtual_bse.py
  kikuchipy/generators/util/virtual_bse.py
  kikuchipy/generators/virtual_bse_generator.py
  kikuchipy/io/__init__.py
  kikuchipy/io/_io.py
  kikuchipy/io/plugins/__init__.py
  kikuchipy/io/plugins/emsoft_ebsd.py
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/h5ebsd.py
  kikuchipy/io/plugins/nordif.py
  kikuchipy/pattern/__init__.py
  kikuchipy/pattern/chunk.py
  kikuchipy/pattern/correlate.py
  kikuchipy/projections/__init__.py
  kikuchipy/projections/ebsd_projections.py
  kikuchipy/projections/hesse_normal_form.py
  kikuchipy/projections/lambert_projection.py
  kikuchipy/projections/spherical_projection.py
  kikuchipy/signals/__init__.py
  kikuchipy/signals/_common_image.py
  kikuchipy/signals/ebsd.py
  kikuchipy/simulations/__init__.py
  kikuchipy/simulations/features.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
  kikuchipy/simulations/tests/test_features.py
Labels: documentation, tests

#225 Set correct shape for gnomonic_radius in KikuchiBand computations
  kikuchipy/simulations/features.py
  kikuchipy/simulations/tests/test_features.py
Labels: bug
