Repository pyxem/kikuchipy, pull requests merged in 2020-11, with the labels that each got.

#242 Fix reading of single energy master pattern from EMsoft EBSDmaster file
  kikuchipy/data/emsoft_ebsd_master_pattern/create_dummy_emsoft_ebsdmasterpatternfile.py
  kikuchipy/data/emsoft_ebsd_master_pattern/master_patterns.h5
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd_masterpattern.py
Labels: :beetle: bug

#243 Add external 13 MB Ni EBSD dataset to module, pooch/tqdm dependencies
  doc/changelog.rst
  doc/contributing.rst
  doc/installation.rst
  doc/load_save_data.ipynb
  doc/pattern_processing.ipynb
  doc/reference.rst
  kikuchipy/data/__init__.py
  kikuchipy/data/_registry.py
  kikuchipy/data/tests/test_data.py
  setup.py
Labels: :tada: enhancement

#244 Replace reST user guide with Jupyter Notebook for image quality guide, remove unused images
  doc/_static/image/feature_maps/image_quality_pattern.jpg
  doc/_static/image/feature_maps/iq.png
  doc/_static/image/pattern_processing/adapthist.jpg
  doc/_static/image/pattern_processing/average_neighbour_pattern.jpg
  doc/_static/image/pattern_processing/contrast_stretching.jpg
  doc/_static/image/pattern_processing/dynamic_correction.jpg
  doc/_static/image/pattern_processing/fft_filter_highlowpass.jpg
  doc/_static/image/pattern_processing/fft_filter_highlowpass_result.jpg
  doc/_static/image/pattern_processing/fft_filter_laplacian.jpg
  doc/_static/image/pattern_processing/get_dynamic_background.jpg
  doc/_static/image/pattern_processing/normalize_intensity.jpg
  doc/_static/image/pattern_processing/pattern_adapthist.jpg
  doc/_static/image/pattern_processing/pattern_dynamic.jpg
  doc/_static/image/pattern_processing/pattern_raw.jpg
  doc/_static/image/pattern_processing/pattern_static.jpg
  doc/_static/image/pattern_processing/rescale_intensities.jpg
  doc/_static/image/pattern_processing/static_correction.jpg
  doc/_static/image/pattern_processing/window_circular_54.png
  doc/_static/image/pattern_processing/window_gaussian_std1.png
  doc/bibliography.bib
  doc/changelog.rst
  doc/feature_maps.ipynb
  doc/feature_maps.rst
  doc/index.rst
  doc/pattern_processing.ipynb
  doc/visualizing_patterns.rst
Labels: :book: documentation

#246 Remove master pattern metadata, add projection, hemisphere and phase attributes
  doc/changelog.rst
  doc/load_save_data.ipynb
  doc/metadata.rst
  doc/reference.rst
  kikuchipy/data/tests/test_data.py
  kikuchipy/io/plugins/emsoft_ebsd.py
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd_masterpattern.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd_masterpattern.py
  kikuchipy/signals/util/__init__.py
  kikuchipy/signals/util/_metadata.py
  kikuchipy/signals/util/tests/test_metadata.py
Labels: :book: documentation, :tada: enhancement

#239 Detector Pattern Simulation
  kikuchipy/data/emsoft_ebsd/EBSD_TEST_Ni.h5
  kikuchipy/projections/lambert_projection.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/tests/test_ebsd_masterpattern.py
Labels: :tada: enhancement

#250 Replace Travis CI with GitHub Actions + IO bug fix
  .github/workflows/build.yml
  .travis.yml
  README.rst
  ci/travis_install_with_conda.sh
  ci/travis_install_with_pip.sh
  ci/travis_setup_conda_linux.sh
  ci/travis_setup_conda_osx.sh
  ci/travis_setup_conda_windows.sh
  doc/changelog.rst
  doc/contributing.rst
  doc/load_save_data.ipynb
  kikuchipy/io/_io.py
  kikuchipy/io/_util.py
  kikuchipy/io/plugins/tests/test_h5ebsd.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/tests/test_ebsd_masterpattern.py
  setup.py
Labels: :beetle: bug, :clipboard: tests, :hammer_and_wrench: maintenance

#255 Sum Lambert projections from asymmetric positions in EMsoft plugin
  doc/changelog.rst
  kikuchipy/data/emsoft_ebsd_master_pattern/create_dummy_emsoft_ebsdmasterpatternfile.py
  kikuchipy/data/emsoft_ebsd_master_pattern/master_patterns.h5
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/projections/tests/test_lambert_projection.py
Labels: :beetle: bug

#256 Add line in coverage config file required by coverage report GitHub Action
  .coveragerc
  .github/workflows/build.yml
  pytest.ini
  setup.cfg
  setup.py
Labels: :hammer_and_wrench: maintenance

#257 Update README, add Binder badge, always build all notebooks
  .github/workflows/build.yml
  README.rst
  doc/changelog.rst
  doc/conf.py
Labels: :book: documentation
