Repository pyxem/kikuchipy, pull requests merged in 2020-10, with the labels that each got.

#226 Add EBSD.xmap class property storing a CrystalMap, read from EMsoft EBSD file
  doc/changelog.rst
  doc/load_save_data.rst
  kikuchipy/io/plugins/emsoft_ebsd.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
Labels: enhancement

#233 Pattern Matching: Compare experimental with simulated data
  doc/changelog.rst
  doc/reference.rst
  kikuchipy/indexing/__init__.py
  kikuchipy/indexing/pattern_matching.py
  kikuchipy/indexing/similarity_metrics.py
  kikuchipy/indexing/tests/test_pattern_matching.py
  kikuchipy/indexing/tests/test_similarity_metrics.py
Labels: :tada: enhancement

#240 EMsoft EBSD master pattern plugin can read a single energy, change energy parameter name
  doc/changelog.rst
  doc/load_save_data.rst
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd_masterpattern.py
Labels: :tada: enhancement

#241 Fix EMsoft PC conversion when inputs are integers (thanks to @friedkitteh)
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/detectors/tests/test_ebsd_detector.py
Labels: :beetle: bug

#237 Add test master pattern to data module, IO notebook replace reST in user guide
  MANIFEST.in
  doc/bibliography.bib
  doc/changelog.rst
  doc/index.rst
  doc/load_save_data.ipynb
  doc/load_save_data.rst
  doc/metadata.rst
  doc/pattern_processing.ipynb
  doc/pattern_processing.rst.bak
  doc/reference.rst
  kikuchipy/data/__init__.py
  kikuchipy/data/emsoft_ebsd_master_pattern/BetheParameters.nml
  kikuchipy/data/emsoft_ebsd_master_pattern/convert_emsoft_ebsd_masterpattern_file_uint8_gzip.py
  kikuchipy/data/emsoft_ebsd_master_pattern/ni.xtal
  kikuchipy/data/emsoft_ebsd_master_pattern/ni_ebsdmaster.nml
  kikuchipy/data/emsoft_ebsd_master_pattern/ni_mc.out
  kikuchipy/data/emsoft_ebsd_master_pattern/ni_mc_mp_20kv_uint8_gzip_opts9.h5
  kikuchipy/data/emsoft_ebsd_master_pattern/ni_mcopencl.nml
  kikuchipy/data/emsoft_ebsd_master_pattern/ni_mp.out
  kikuchipy/data/tests/test_data.py
Labels: :book: documentation, :hammer_and_wrench: maintenance, :tada: enhancement
