Repository pyxem/kikuchipy, pull requests merged in 2021-01, with the labels that each got.

#271 Swap row and column coordinates in the modified Lambert projection
  kikuchipy/signals/ebsd_master_pattern.py
Labels: :beetle: bug

#273 Fix LambertProjection.project() handling of a [0, 0, 1] vector
  doc/changelog.rst
  kikuchipy/projections/lambert_projection.py
  kikuchipy/projections/tests/test_lambert_projection.py
Labels: :beetle: bug

#276 Write/read support for EBSD signal with 0/1 navigation dimension in kikuchipy's h5ebsd format
  doc/changelog.rst
  kikuchipy/io/plugins/h5ebsd.py
  kikuchipy/io/plugins/nordif.py
  kikuchipy/io/plugins/tests/test_h5ebsd.py
  kikuchipy/signals/ebsd.py
Labels: :tada: enhancement

#275 Make EBSDMasterPattern.get_patterns() allow a 2D navigation shape + minor improvements
  doc/change_scan_pattern_size.ipynb
  doc/changelog.rst
  doc/load_save_data.ipynb
  doc/pattern_matching.ipynb
  doc/reference.rst
  doc/visualizing_patterns.ipynb
  kikuchipy/data/__init__.py
  kikuchipy/data/tests/test_data.py
  kikuchipy/io/_io.py
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd_masterpattern.py
  kikuchipy/pattern/tests/test_chunk.py
  kikuchipy/signals/_common_image.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd_masterpattern.py
  kikuchipy/signals/util/__init__.py
  kikuchipy/signals/util/_dask.py
  kikuchipy/signals/util/tests/test_dask.py
Labels: :tada: enhancement

#278 Overwrite HyperSpy's compute() w/ EBSD.xmap carried over
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
Labels: :beetle: bug

#279 Virtual backscatter electron imaging RST to notebook
  doc/_static/image/virtual_backscatter_electron_imaging/images.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/plot_grid.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/rgb_image.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/rgba_image.jpg
  doc/_static/image/virtual_backscatter_electron_imaging/virtual_backscatter_electron_imaging.gif
  doc/bibliography.bib
  doc/changelog.rst
  doc/index.rst
  doc/virtual_backscatter_electron_imaging.ipynb
  doc/virtual_backscatter_electron_imaging.rst
Labels: :book: documentation

#282 Update diffsims dependency and getting hkl data from ReciprocalLatticePoint
  doc/changelog.rst
  kikuchipy/conftest.py
  kikuchipy/crystallography/_computations.py
  kikuchipy/crystallography/tests/test_crystallographic_computations.py
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/detectors/tests/test_ebsd_detector.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/generators/tests/test_ebsd_simulation_generator.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
  kikuchipy/simulations/tests/test_features.py
  setup.py
Labels: :beetle: bug, :hammer_and_wrench: maintenance

#281 Geometrical EBSD simulation notebook
  README.rst
  doc/bibliography.bib
  doc/changelog.rst
  doc/geometrical_ebsd_simulations.ipynb
  doc/index.rst
  doc/pattern_matching.ipynb
  doc/reference_frames.rst
  kikuchipy/conftest.py
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/generators/tests/test_ebsd_simulation_generator.py
  kikuchipy/projections/ebsd_projections.py
  kikuchipy/projections/tests/test_ebsd_projections.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
  kikuchipy/simulations/tests/test_features.py
  kikuchipy/simulations/tests/test_geometrical_ebsd_simulation.py
Labels: :beetle: bug, :book: documentation

#283 Replace reference frame reST documentation file with notebook
  doc/_static/image/concatenate_images.sh
  doc/_static/image/create_images.sh
  doc/_static/image/doc_feature_maps_images.py
  doc/_static/image/doc_processing_images.py
  doc/_static/image/doc_virtual_imaging.py
  doc/_static/image/doc_visualize_images.py
  doc/_static/image/reference_frames/detector_sample_geometry.png
  doc/_static/image/reference_frames/detector_sample_geometry.svg
  doc/_static/image/reference_frames/pattern.png
  doc/_static/image/remove_images_not_in_docs.sh
  doc/reference_frames.ipynb
  doc/reference_frames.rst
Labels: :book: documentation

#285 Add metadata, MVA notebooks, update README with Sphinx gallery
  README.rst
  doc/bibliography.bib
  doc/change_navigation_signal_shapes.ipynb
  doc/changelog.rst
  doc/conf.py
  doc/contributing.rst
  doc/feature_maps.ipynb
  doc/geometrical_ebsd_simulations.ipynb
  doc/index.rst
  doc/load_save_data.ipynb
  doc/metadata.rst
  doc/metadata_structure.ipynb
  doc/multivariate_analysis.ipynb
  doc/multivariate_analysis.rst
  doc/open_datasets.rst
  doc/pattern_matching.ipynb
  doc/pattern_processing.ipynb
  doc/reference_frames.ipynb
  doc/virtual_backscatter_electron_imaging.ipynb
  doc/visualizing_patterns.ipynb
  kikuchipy/data/__init__.py
  kikuchipy/release.py
  setup.py
Labels: :book: documentation, :hammer_and_wrench: maintenance

#280 Average dot product, neighbour dot product matrices, map helper, rework averaging
  README.rst
  doc/bibliography.bib
  doc/changelog.rst
  doc/feature_maps.ipynb
  doc/pattern_matching.ipynb
  doc/reference.rst
  kikuchipy/filters/tests/test_window.py
  kikuchipy/filters/window.py
  kikuchipy/indexing/similarity_metrics.py
  kikuchipy/pattern/_pattern.py
  kikuchipy/pattern/chunk.py
  kikuchipy/pattern/tests/test_chunk.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/util/_dask.py
  kikuchipy/signals/util/_map_helper.py
Labels: :tada: enhancement

#290 Fix output chunks in ADP calculations
  README.rst
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
Labels: :beetle: bug

#291 Simplify use of Dask in EBSD.average_neighbour_pattern()
  doc/pattern_matching.ipynb
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
Labels: :hammer_and_wrench: maintenance

#292 Prepare for v0.3.0 release with multiple minor changes
  doc/changelog.rst
  doc/conf.py
  doc/contributing.rst
  doc/geometrical_ebsd_simulations.ipynb
  doc/installation.rst
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#293 Merge v0.3.x into master as part of release preparations
  doc/changelog.rst
  doc/conf.py
  doc/contributing.rst
  doc/geometrical_ebsd_simulations.ipynb
  doc/installation.rst
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#294 Increment minor version to v0.4.0dev
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#296 Make first release candidate for v0.3.0
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#297 Remove release candidate part of version
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#298 Update release guide
  .github/pull_request_template.md
  RELEASE.rst
Labels: :hammer_and_wrench: maintenance

#301 Fix release version links used by Binder and nbsphinx
  RELEASE.rst
  doc/changelog.rst
  doc/conf.py
  doc/pattern_matching.ipynb
  kikuchipy/release.py
Labels: :beetle: bug, :book: documentation, :point_left: backport

#303 Backport #301
  RELEASE.rst
  doc/changelog.rst
  doc/conf.py
  doc/pattern_matching.ipynb
  kikuchipy/release.py
Labels: :beetle: bug, :book: documentation

#305 Increment version again from 0.3.1 in release.py
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#307 Fix creation of spatial arrays for CrystalMap after pattern matching
  doc/changelog.rst
  doc/pattern_matching.ipynb
  kikuchipy/indexing/_static_pattern_matching.py
  kikuchipy/indexing/tests/test_static_pattern_matching.py
Labels: :beetle: bug, :point_left: backport
