Repository pyxem/kikuchipy, pull requests merged in 2021-07, with the labels that each got.

#391 Greatly improve reading of EBSD patterns from Oxford Instruments' binary .ebsp file format
  doc/changelog.rst
  doc/load_save_data.ipynb
  doc/reference.rst
  kikuchipy/conftest.py
  kikuchipy/data/oxford_binary/create_dummy_oxford_binary_file.py
  kikuchipy/data/oxford_binary/patterns.ebsp
  kikuchipy/io/plugins/oxford_binary.py
  kikuchipy/io/plugins/tests/test_oxford_binary.py
Labels: :tada: enhancement

#392 Fix row (y) coordinate array in crystal map returned from dictionary indexing
  doc/changelog.rst
  kikuchipy/indexing/_static_pattern_matching.py
  kikuchipy/indexing/tests/test_static_pattern_matching.py
Labels: :beetle: bug

#393 Update changelog and release version for a v0.4.0 minor release
  doc/changelog.rst
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#395 Set minimal requirement of importlib_metadata
  doc/changelog.rst
  setup.py
Labels: :beetle: bug

#396 Update installation instructions and add warning
  doc/installation.rst
Labels: :book: documentation

#397 Merge v0.4.x into master
  doc/changelog.rst
  doc/installation.rst
  kikuchipy/release.py
  setup.py
Labels: :hammer_and_wrench: maintenance

#398 Post v0.4.0 updates to master
  doc/changelog.rst
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#400 Acknowledge that Oxford Instruments' provided info about the .ebsp file format
  kikuchipy/io/plugins/oxford_binary.py
Labels: :book: documentation

#387 Refinement Module
  doc/bibliography.bib
  doc/changelog.rst
  kikuchipy/indexing/_refinement.py
  kikuchipy/indexing/tests/test_refinement.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/tests/test_ebsd_masterpattern.py
Labels: :tada: enhancement
