Repository pyxem/kikuchipy, pull requests merged in 2022-06, with the labels that each got.

#532 Improve control of memory use in EBSD neighbour pattern averaging
  CHANGELOG.rst
  doc/user_guide/pattern_matching.ipynb
  kikuchipy/pattern/_pattern.py
  kikuchipy/pattern/chunk.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/util/_dask.py
Labels: :lady_beetle: bug

#533 Deprecate instead of removing three chunk processing functions
  CHANGELOG.rst
  doc/reference.rst
  kikuchipy/pattern/chunk.py
  kikuchipy/pattern/tests/test_chunk.py
Labels: :pencil2: deprecation

#536 Plot spherical master pattern
  .github/workflows/build.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  doc/conf.py
  doc/installation.rst
  doc/reference.rst
  doc/user_guide/visualizing_patterns.ipynb
  kikuchipy/__init__.py
  kikuchipy/conftest.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd_master_pattern.py
  readthedocs.yaml
  setup.py
Labels: :tada: enhancement

#537 Geometrical and kinematical Kikuchi pattern simulations for all point groups
  .github/workflows/build.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  doc/bibliography.bib
  doc/examples/mandm2021_sunday_short_course.ipynb
  doc/index.rst
  doc/reference.rst
  doc/user_guide/geometrical_ebsd_simulations.ipynb
  doc/user_guide/kikuchi_pattern_simulations.ipynb
  doc/user_guide/load_save_data.ipynb
  doc/user_guide/pattern_processing.ipynb
  doc/user_guide/reference_frames.ipynb
  kikuchipy/_util/_util.py
  kikuchipy/conftest.py
  kikuchipy/crystallography/matrices.py
  kikuchipy/crystallography/tests/test_crystallographic_matrices.py
  kikuchipy/data/__init__.py
  kikuchipy/data/tests/test_data.py
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/detectors/tests/test_ebsd_detector.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/generators/tests/test_ebsd_simulation_generator.py
  kikuchipy/generators/virtual_bse_generator.py
  kikuchipy/indexing/_refinement/_objective_functions.py
  kikuchipy/io/plugins/emsoft_ebsd_master_pattern.py
  kikuchipy/io/plugins/tests/test_emsoft_ebsd_masterpattern.py
  kikuchipy/projections/ebsd_projections.py
  kikuchipy/signals/ebsd.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/signals/tests/test_ebsd.py
  kikuchipy/signals/tests/test_ebsd_master_pattern.py
  kikuchipy/signals/util/_master_pattern.py
  kikuchipy/simulations/__init__.py
  kikuchipy/simulations/_kikuchi_pattern_features.py
  kikuchipy/simulations/_kikuchi_pattern_simulation.py
  kikuchipy/simulations/features.py
  kikuchipy/simulations/geometrical_ebsd_simulation.py
  kikuchipy/simulations/kikuchi_pattern_simulator.py
  kikuchipy/simulations/tests/test_geometrical_ebsd_simulation.py
  kikuchipy/simulations/tests/test_kikuchi_pattern_simulation.py
  kikuchipy/simulations/tests/test_kikuchi_pattern_simulator.py
  setup.py
Labels: :lady_beetle: bug, :tada: enhancement, :book: documentation, port-diffsims, :pencil2: deprecation

#539 Post release v0.6.0 merge main into develop
  CHANGELOG.rst
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#545 Post release v0.6.1 main into develop
  .github/workflows/build.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  MANIFEST.in
  environment.yml
  kikuchipy/detectors/ebsd_detector.py
  kikuchipy/generators/ebsd_simulation_generator.py
  kikuchipy/release.py
  kikuchipy/signals/ebsd_master_pattern.py
  kikuchipy/simulations/_kikuchi_pattern_simulation.py
Labels: :hammer_and_wrench: maintenance

#546 Post 0.6.1 updates to develop
  .github/workflows/merge_main_into_develop.yml
  kikuchipy/release.py
Labels: :hammer_and_wrench: maintenance

#549 Fix minor typo in docstring
  .all-contributorsrc
  .github/pull_request_template.md
  README.md
  kikuchipy/release.py
  kikuchipy/signals/ebsd.py
Labels: :book: documentation
