Repository pyxem/kikuchipy, pull requests merged in 2023-03, with the labels that each got.

#623 Set minimal version of orix to >= 0.11.1
  .all-contributorsrc
  .github/workflows/tests.yml
  .zenodo.json
  CHANGELOG.rst
  README.md
  kikuchipy/release.py
  setup.py
Labels: bug

#624 Main into develop post 0.8.2 release
  .all-contributorsrc
  .github/workflows/tests.yml
  .zenodo.json
  CHANGELOG.rst
  README.md
  RELEASE.rst
  kikuchipy/release.py
  setup.py
Labels: maintenance

#625 Temporarily disable PDF build
  doc/conf.py
  readthedocs.yaml
Labels: documentation
